### ISSUE TITLE
期望功能添加

### ISSUE THREAD

**Issue by RacerZ-fighting** [tw93/weekly#128]
希望作者可以添加一个检索功能，方便查阅以前文章当中的内容。当前想找之前的某个内容时，只能通过 google search intext: 这种方式来筛选

**Comment by tw93** [comment]
哈哈 其实支持的，你看首页 以及 阅读页标题旁边是不是有一个 🔍按钮，甚至全局按下/ 也可以唤起

**Comment by RacerZ-fighting** [comment]
> 哈哈 其实支持的，你看首页 以及 阅读页标题旁边是不是有一个 🔍按钮，甚至全局按下/ 也可以唤起

哦哦感谢！
