### ISSUE TITLE
关于图床询问alipayobjects

### ISSUE THREAD

**Issue by itgoyo** [tw93/weekly#136]
哈喽，大佬，看到你这边的图片都是用alipayobjects的图床链接，但是我在搜索的时候，并没搜索到任何相关alipayobjects的图床入口，看到还有很多阿里相关的文档引用也是这个图床的，这个是内部使用的么？还是说有图床入口的，因为发现即便是没有外网的环境下面加载改图床的图片还是挺快的。

**Comment by tw93** [comment]
这个周刊的起源其实是首发内部的，后面有一些同学离开，也想看，由于没有任何保密信息就随手做了一个外部的网站。
