### ISSUE TITLE
建议增加网页提醒

### ISSUE THREAD

**Issue by APLaS-Plus** [tw93/weekly#138]
建议增加网页提醒，像YouTube和X那种，有时候是想看的但是忘了会更新

**Comment by tw93** [comment]
很推荐使用NetNewsWire来订阅
https://weekly.tw93.fun/rss.xml

**Comment by APLaS-Plus** [comment]
NetNewsWire只支持苹果全家桶啊，作者大大有无windows的推荐🫡

**Comment by tw93** [comment]
试试 [Fluent Reader](https://www.appinn.com/fluent-reader/)
