### ISSUE TITLE
report a bug 

### ISSUE THREAD

**Issue by liam-pat** [tw93/weekly#143]
hola,
如果文章只有一篇，會 build 失敗，猜測是計算分頁信息那裡有問題

**Comment by tw93** [comment]
谢谢反馈 下次我改改，其实你可以给我提pr 哈哈

**Comment by Apecice** [comment]
现在已修复保留顺序的篇章（如：1、2篇）正常，比如像我保留178/179则会异常 😄

**Comment by liam-pat** [comment]
> 谢谢反馈 下次我改改，其实你可以给我提pr 哈哈

等你 fix 啦，哈哈，我看不懂前端語法，用了什麼技術棧都不知道。
你的風格很好，給你點讚呀~~有機會可以交個朋友
