### ISSUE TITLE
评论系统有时在暗色系下会展示亮色系样式

### ISSUE THREAD

**Issue by tyj-321** [tw93/weekly#161]
好像评论系统有时候是懒加载的，当我在还没有加载出来的时候，切换成暗色系，评论会仍然是亮色系样式

![image](https://github.com/user-attachments/assets/eb5f98fe-e435-4e92-a575-cc98737f208f)

我本来想fork代码尝试改下的，但是我分别使用了node 16和node 18运行npm install 然后 npm run dev都失败了😢

**Comment by tw93** [comment]
看看报错，node 18 没有问题的
这个问题我也去看看，当然假如你可以提供pr那就太好了，运行我记得有一个fork文档使用，在仓库里面

**Comment by tyj-321** [comment]
本地node版本  v18.20.3

![image](https://github.com/user-attachments/assets/02c28089-d6d0-4dd5-b5a9-a8f6024368bb)

运行npm run dev

![image](https://github.com/user-attachments/assets/5b025f02-7b09-4286-bf0c-aee1d1451e6d)

但是打开网页后报错

![image](https://github.com/user-attachments/assets/bacb2dae-d72a-4a28-a574-fe1690ce3def)
![image](https://github.com/user-attachments/assets/3001a44f-7e9a-4bdb-b856-5bee65187851)


顺便我说下复现步骤，用亮色系打开某一期内容，然后切换成暗色系，然后滚动到底部，会看到评论在加载，加载完后就是亮色系样式

感觉可以在评论加载完的时候再判断切换下样式文件即可，我乐意提供pr，(不过我对Astro并不是特别熟悉😶)

**Comment by tw93** [comment]
初步看是这里windows的机器运行有些问题，可以简单debug一下，代码本身编译看着没有问题的
<img width="495" alt="image" src="https://github.com/user-attachments/assets/e3037d91-eec5-45f2-bb23-c7e558d7a8ae">

**Comment by tw93** [comment]
我简单改了改 你可以去看看 diff 不过不一定还有没有 bug 后面我没有复现

**Comment by tyj-321** [comment]
> 初步看是这里windows的机器运行有些问题，可以简单debug一下，代码本身编译看着没有问题的，目录看着不是fork的，而是下载的，目录应该是 weekly，不是weekly-main <img alt="image" width="495" src="https://private-user-images.githubusercontent.com/8736212/355333758-e3037d91-eec5-45f2-bb23-c7e558d7a8ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzMyNDcsIm5iZiI6MTcyMjkzMjk0NywicGF0aCI6Ii84NzM2MjEyLzM1NTMzMzc1OC1lMzAzN2Q5MS1lZWM1LTQ1ZjItYmIyMy1jN2U1NThkN2E4YWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDZUMDgyOTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGIxZDcxMWU0NDY3MDEwZjA1NzQ0OGU4YmFlMTNmMTVjOTMxYjNiYmVhZWMyNmU4OTU0MGYzOTBjNzQ4NDkxZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8mXc58tnpcJiPrdLOVkq7ogNSPIUdFetEYqJ54sGb1Y">

是的，由于网络的原因，我是直接download code的压缩包，然后文件会带上一个-main 即为分支



> 我简单改了改 你可以去看看 diff 不过不一定还有没有 bug 后面我没有复现

你的这次提交，会直接部署上去么？看起来问题似乎得到了解决 👀

**Comment by tw93** [comment]
弄软件专业的 还是需要学会科学上网哦 很有必要
嗯嗯 每次提交会有自动运行的钩子去发布
