### ISSUE TITLE
RSS订阅链接 SSL证书似乎过期

### ISSUE THREAD

**Issue by vstar37** [tw93/weekly#168]
你好，https://weekly.tw93.fun/rss.xml 似乎无法正常订阅。

**Comment by KrabsWong** [comment]
<img width="590" alt="image" src="https://github.com/user-attachments/assets/e1a8dd51-e4c1-41ec-81d1-bcb56292925f">

看起来还可以？11月份到期

**Comment by vstar37** [comment]
可以订阅了  应该是我的问题 抱歉。
