### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by Kafka3** [tw93/weekly#19]
在npm run dev时出现
error   Cannot find module '/Users/Documents/GitHub/weekly/src/config' imported from /Users/Documents/GitHub/weekly/astro.config.mjs
请问您知道如何解决吗？

**Comment by tw93** [comment]
/Users/Documents/GitHub/weekly/astro.config.mjs
看看这个文件 此外node版本需要新一点

**Comment by Kafka3** [comment]
import { SITE } from './src/config';
导入的没有问题呀
node v19.1.0
感谢回复

**Comment by tw93** [comment]
使用16版本或者14版本的 直接无改动的方式试试我这边原始的项目，你就可以发现哪儿有问题的规律了
