### ISSUE TITLE
咨询，Card.astro如何获取md文件中的第一个图片？

### ISSUE THREAD

**Issue by xinmans** [tw93/weekly#43]
index.astro 

        {allPosts.map((p) => <Card post={p} />)}

==> 

src/components/Card.astro

const { post } = Astro.props;
const title = parseTitle(post.url);
const { pic, desc, date } = post.frontmatter;

pic和desc是如何自动从md文档中获取的？

如果md中的第一张图片是
![]()格式，非<img src>格式，那又该如何获取？

**Comment by tw93** [comment]
astro.config.mjs
参考一下这个文件实现就好
