### ISSUE TITLE
第146期内容有误

### ISSUE THREAD

**Issue by xxholly32** [tw93/weekly#84]
把网页转换成 Markdown 格式存储 

https://tuulih6pyq.feishu.cn/wiki/AVhMwAP14iXVKxkc32ackfGInAc 发现一个超级全的设计师知识库「年少的游戏厅」，基本上可以当做新一代入门设计师的一些知识全面了解，包括书签收藏、作品集、视觉设计、用户研究、B 端设计等方面，比较适合收藏着有时间慢慢看一遍。

感觉这个标题和里面的内容不符合，在设计师的知识库也没找到 `把网页转换成 Markdown 格式存储 ` 这个文献

**Comment by tw93** [comment]
感谢反馈，已经修正，应该是我昨晚喝醉了😵‍💫
